### PR TITLE
Fix# 774 - Fixes File Still Required when Correct

### LINKED ISSUE #774: Distribute funds: file is still required after CSV was processed
grafik

### PR DESCRIPTION
**Pull request by abefernan**
Closes #774.

### CODE REVIEW

File: packages/sil-governance/src/routes/create-proposal/components/FormOptions/DistributeFunds/index.tsx [hunk 1]
```diff
@@ -59,6 +60,10 @@ const DistributeFunds = ({ form, recipientsChanged }: Props): JSX.Element => {
         setRecipients(recipients);
         recipientsChanged(recipients);
       } catch (error) {
+        // TODO the value of an input file can only be set to empty string, not working
+        (document.getElementById(IMPORT_FIELD_ID) as HTMLInputElement).value = "";
```
Comment (webmaster128) [inline packages/sil-governance/src/routes/create-proposal/components/FormOptions/DistributeFunds/index.tsx]: The issue with this approach is that it only changes the rendered html component, not the state that remains unchanged in the React component. Let's better not access DOM directly like this

File: packages/sil-governance/src/routes/create-proposal/components/FormOptions/DistributeFunds/index.tsx [hunk 2]
```diff
@@ -73,16 +76,17 @@ const DistributeFunds = ({ form, recipientsChanged }: Props): JSX.Element => {
   return (
     <React.Fragment>
       <Block marginTop={2} display="flex" alignItems="center">
-        <Typography>{IMPORT_FIELD}</Typography>
+        <Typography>{IMPORT_FIELD_NAME}</Typography>
         <Block marginLeft={2}>
           <TextField
-            name={IMPORT_FIELD}
+            name={IMPORT_FIELD_NAME}
+            id={IMPORT_FIELD_ID}
```
Comment (webmaster128) [inline packages/sil-governance/src/routes/create-proposal/components/FormOptions/DistributeFunds/index.tsx]: Can we remove this ID as well?
