### PR TITLE
Fix #708 – Stabilize submitExtensionCreateWalletForm

### LINKED ISSUE #708: Fix instable test
```
sil-governance: FAIL src/routes/login/index.e2e.spec.ts (34.957s)
sil-governance:   E2E > Login route
sil-governance:     ✓ should redirect when enqueued login request is accepted (13209ms)
sil-governance:     ✕ should stay in login view if enqueued login request is rejected (8332ms)
sil-governance:     ✓ shows login to IOV extension if not persona detected (5210ms)
sil-governance:     ✓ shows install IOV extension message (4672ms)
sil-governance:   ● E2E > Login route › should stay in login view if enqueued login request is rejected
sil-governance:     Node is either not visible or not an HTMLElement
sil-governance:       23 |   await sleep(1000);
sil-governance:       24 |   const buttons = await page.$$("button");
sil-governance:     > 25 |   await buttons[1].click();
sil-governance:          |   ^
sil-governance:       26 |   await page.click('button[type="submit"]');
sil-governance:       27 |   await whenOnNavigatedToE2eRoute(page, "/wallet");
sil-governance:       28 | };
sil-governance:       at ElementHandle._clickablePoint (../../node_modules/puppeteer/lib/JSHandle.js:199:13)
sil-governance:           at runMicrotasks (<anonymous>)
sil-governance:       at ElementHandle.click (../../node_modules/puppeteer/lib/JSHandle.js:265:20)
sil-governance:       at submitExtensionSignupForm (src/utils/test/persona.ts:25:3)
sil-governance:       at Object.<anonymous> (src/routes/login/index.e2e.spec.ts:85:5)
```

from https://travis-ci.com/iov-one/ponferrada/builds/127180067

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #708

### CODE REVIEW

File: packages/bierzo-wallet/src/utils/test/persona.ts [hunk 1]
```diff
@@ -21,9 +21,13 @@ export const submitExtensionCreateWalletForm = async (page: Page, password: stri
   await page.type(`input[name="${PASSWORD_CONFIRM_FIELD}"]`, password);
   await page.click(`input[name="${TERMS_ACCEPT_FIELD}"]`);
   await page.click('button[type="submit"]');
-  await sleep(1000);
+  await sleep(1500); // TODO: find direct way to detect if page was change to next step
```
Comment (albertandrejev) [inline packages/bierzo-wallet/src/utils/test/persona.ts]: We can use `waitFor` puppeteer api method (https://github.com/GoogleChrome/puppeteer/blob/v1.20.0/docs/api.md#pagewaitforselectororfunctionortimeout-options-args). We can wait for next step id in this case this is `SECOND_STEP_CREATE_WALLET_ROUTE` from packages/sanes-browser-extension/src/routes/create-wallet/components/ShowPhraseForm.tsx

File: packages/sil-governance/src/utils/test/persona.ts [hunk 2]
```diff
@@ -20,9 +20,13 @@ export const submitExtensionCreateWalletForm = async (page: Page, password: stri
   await page.type(`input[name="${PASSWORD_CONFIRM_FIELD}"]`, password);
   await page.click(`input[name="${TERMS_ACCEPT_FIELD}"]`);
   await page.click('button[type="submit"]');
-  await sleep(1000);
+  await sleep(1500); // TODO: find direct way to detect if page was change to next step
```
Comment (albertandrejev) [inline packages/sil-governance/src/utils/test/persona.ts]: `waitFor` api call.

File: packages/bierzo-wallet/src/utils/test/persona.ts (hunk 1 above)
Comment (webmaster128) [reply packages/bierzo-wallet/src/utils/test/persona.ts]: Good idea.

So we would do

```ts
await page.waitForSelector(`#${SECOND_STEP_CREATE_WALLET_ROUTE}`);
```

? I was already thinking in the direction but only with routes (https://github.com/iov-one/ponferrada/issues/729). But it would be nice if the routes are not necessary to fix this.

Comment (albertandrejev) [reply packages/bierzo-wallet/src/utils/test/persona.ts]: Yes, you're right, this is exactly what I had in mind. Routes is not required in this case, also there is no route changes between wallet creation steps.

Comment (webmaster128) [reply packages/bierzo-wallet/src/utils/test/persona.ts]: Great, much better than the sleeps as it will save much testing time on average and is more stable in slow situations

Comment (albertandrejev) [reply packages/bierzo-wallet/src/utils/test/persona.ts]: And in this case #729 is not required any more.

Comment (webmaster128) [reply packages/bierzo-wallet/src/utils/test/persona.ts]: I implemented the suggested approach now. Much better! Main commit for the fix is https://github.com/iov-one/ponferrada/pull/728/commits/7975d6971841c0027869007aa7312607a1b1ea5b
