### PR TITLE
Fix #898 - Fixes SidePanel and removes Wallet errors

### LINKED ISSUE #898: Fix wallet error messages during E2E tests
Build  2021   iov one ponferrada   Travis CI

### PR DESCRIPTION
**Pull request by abefernan**
Closes #898.

### CODE REVIEW

File: packages/sanes-browser-extension/src/routes/wallet/components/SidePanel/PanelDrawer/components/Requests/ShowRequest/index.tsx [hunk 1]
```diff
@@ -26,6 +26,7 @@ const ShowRequest = ({ goBackToList }: Props): JSX.Element => {
 
   const closeExtension = (): void => {
     if (requestContext.requests.length === 0) {
+      goBackToList();
```
Comment (albertandrejev) [inline packages/sanes-browser-extension/src/routes/wallet/components/SidePanel/PanelDrawer/components/Requests/ShowRequest/index.tsx]: You can move it out of the if condition. Also please leave comment about this behaviour.
